// MPEP Quiz Bank — curated questions covering major chapters
// Source: USPTO MPEP, Ninth Edition, Revision 01.2024
// Each question: { id, chapter, topic, q, choices: [A-D], answer: 0-3, explain, cite }

window.MPEP_QUESTIONS = [
  // ─────────────────────── Chapter 200 — Application Types & Status ───────────────────────
  {chapter:"200", topic:"Application Types", q:"A provisional application is automatically abandoned how long after its filing date?",
    choices:["6 months","12 months","18 months","It is never automatically abandoned"], answer:1,
    explain:"A provisional becomes automatically abandoned 12 months after filing and cannot be revived. It does not get examined and does not mature into a patent on its own.",
    cite:"MPEP §201.04"},
  {chapter:"200", topic:"Continuations", q:"Which of the following is a requirement for a continuation application under 35 U.S.C. 120?",
    choices:["Must be filed before issuance or abandonment of the parent","Must add new matter","Must be filed by a different inventor","Must claim a different invention"], answer:0,
    explain:"A continuation must be co-pending with the parent — filed before the parent issues, is abandoned, or terminates. It cannot add new matter.",
    cite:"MPEP §201.07"},
  {chapter:"200", topic:"CIP", q:"A continuation-in-part (CIP) application:",
    choices:["Cannot share any subject matter with the parent","May add new matter not disclosed in the parent","Must be filed within 6 months of the parent","Is the same as a divisional application"], answer:1,
    explain:"A CIP repeats substantial portions of the parent and adds new matter. Claims supported only by the new matter get the CIP's filing date, not the parent's.",
    cite:"MPEP §201.08"},
  {chapter:"200", topic:"Foreign Priority", q:"Under 35 U.S.C. 119(a), a U.S. application claiming foreign priority must be filed within how long of the foreign filing?",
    choices:["6 months","12 months","18 months","2 years"], answer:1,
    explain:"Paris Convention priority must be claimed within 12 months for utility applications (6 months for designs).",
    cite:"MPEP §213"},

  // ─────────────────────── Chapter 600 — Parts, Form & Content ───────────────────────
  {chapter:"600", topic:"Specification", q:"The specification must contain a written description, enablement, and:",
    choices:["A drawing","Best mode","Industrial applicability","A prior art statement"], answer:1,
    explain:"35 U.S.C. 112(a) requires written description, enablement, and best mode. Failure to disclose best mode is no longer a basis for invalidity in litigation post-AIA, but the requirement still exists during examination.",
    cite:"MPEP §608.01, §2165"},
  {chapter:"600", topic:"Drawings", q:"When are drawings required in a utility patent application?",
    choices:["Always","Only when the invention is mechanical","When necessary for the understanding of the subject matter","Only if claimed"], answer:2,
    explain:"35 U.S.C. 113 requires drawings only when necessary for understanding the invention. Chemical/process inventions often need none.",
    cite:"MPEP §608.02"},
  {chapter:"600", topic:"Claims", q:"A claim that incorporates by reference all the limitations of another claim is a:",
    choices:["Independent claim","Dependent claim","Multiple dependent claim","Jepson claim"], answer:1,
    explain:"A dependent claim references and further limits another claim. A multiple dependent claim refers to more than one claim in the alternative.",
    cite:"MPEP §608.01(n)"},
  {chapter:"600", topic:"Multiple Dependent Claims", q:"A proper multiple dependent claim may:",
    choices:["Depend on multiple claims in the alternative only","Depend on multiple claims cumulatively","Serve as a basis for another multiple dependent claim","Include new matter"], answer:0,
    explain:"35 U.S.C. 112(e) requires multiple dependent claims to refer to other claims 'in the alternative only,' and they cannot serve as a basis for further multiple dependent claims.",
    cite:"MPEP §608.01(n)"},
  {chapter:"600", topic:"Oath/Declaration", q:"Which statement about the inventor's oath or declaration under the AIA is correct?",
    choices:["Must be filed on the filing date","May be postponed until payment of the issue fee","Cannot be made by an assignee","Must be notarized"], answer:1,
    explain:"Under the AIA, the inventor's oath or declaration may be postponed until the application is otherwise in condition for allowance (issue fee due).",
    cite:"MPEP §602"},

  // ─────────────────────── Chapter 700 — Examination ───────────────────────
  {chapter:"700", topic:"Office Action Response", q:"The statutory period for reply to a non-final office action is generally:",
    choices:["1 month","3 months, extendable to 6","6 months, non-extendable","12 months"], answer:1,
    explain:"The statutory maximum is 6 months. The shortened statutory period is usually 3 months, extendable up to 6 months total with fees under 37 CFR 1.136(a).",
    cite:"MPEP §710.02"},
  {chapter:"700", topic:"Final Rejection", q:"After a final rejection, which is NOT generally entered as a matter of right?",
    choices:["An amendment cancelling claims","A reply complying with the final rejection","An amendment presenting claims in better form","An amendment raising new issues requiring further search"], answer:3,
    explain:"After final, amendments that raise new issues or require further search/consideration are not entered as a matter of right. RCE or appeal is typically needed.",
    cite:"MPEP §714.13"},
  {chapter:"700", topic:"RCE", q:"A request for continued examination (RCE) requires:",
    choices:["A new oath","A submission and the prescribed fee","A new inventor","A continuation application"], answer:1,
    explain:"An RCE under 37 CFR 1.114 requires a submission (e.g., amendment, IDS, arguments) and the RCE fee. It reopens prosecution without filing a new application.",
    cite:"MPEP §706.07(h)"},
  {chapter:"700", topic:"After Final", q:"An applicant's first reply after final rejection that does not place the application in condition for allowance:",
    choices:["Restarts the period for reply","Does not toll the period for reply","Is automatically not entered","Requires payment of the issue fee"], answer:1,
    explain:"Filing a first reply after final does not toll or restart the 3-month shortened statutory period; the applicant must still respond within the statutory period to avoid abandonment.",
    cite:"MPEP §714.13"},
  {chapter:"700", topic:"Interview", q:"Interviews after final rejection are:",
    choices:["A matter of right","Granted at the examiner's discretion","Prohibited","Limited to telephone only"], answer:1,
    explain:"Before final, interviews are generally granted as a matter of right. After final, they are at the examiner's discretion.",
    cite:"MPEP §713.09"},

  // ─────────────────────── Chapter 800 — Restriction ───────────────────────
  {chapter:"800", topic:"Restriction", q:"A restriction requirement is proper when:",
    choices:["Two or more independent and distinct inventions are claimed","The application has more than 20 claims","The applicant requests it","The claims are unclear"], answer:0,
    explain:"Under 35 U.S.C. 121, restriction is proper when two or more independent and distinct inventions are claimed in one application.",
    cite:"MPEP §803"},
  {chapter:"800", topic:"Election", q:"After a restriction requirement, applicant must:",
    choices:["File a divisional immediately","Elect one invention for prosecution, with or without traverse","Abandon non-elected claims","File an appeal"], answer:1,
    explain:"Applicant must elect one invention to prosecute. Election may be made with or without traverse; non-elected claims can be pursued in a divisional.",
    cite:"MPEP §818"},

  // ─────────────────────── Chapter 1200 — Appeal ───────────────────────
  {chapter:"1200", topic:"Appeal", q:"An appeal to the PTAB requires that claims have been:",
    choices:["Rejected once","Twice rejected","Finally rejected only","Allowed"], answer:1,
    explain:"Under 35 U.S.C. 134, an appeal is available after any claim has been twice rejected, regardless of whether the rejection is final.",
    cite:"MPEP §1204"},
  {chapter:"1200", topic:"Notice of Appeal", q:"A notice of appeal must be filed within:",
    choices:["1 month of the office action","The period set for reply (typically 3 months, extendable)","2 months of the final rejection","6 months, non-extendable"], answer:1,
    explain:"The notice of appeal must be filed within the period for reply to the office action — usually 3 months, extendable up to 6 months under 1.136(a).",
    cite:"MPEP §1204"},
  {chapter:"1200", topic:"Appeal Brief", q:"After filing a notice of appeal, the appeal brief is due within:",
    choices:["1 month","2 months from notice of appeal","3 months from notice of appeal, extendable","6 months, non-extendable"], answer:1,
    explain:"The appeal brief must be filed within 2 months from the date of the notice of appeal, extendable under 1.136(a).",
    cite:"MPEP §1205"},
  {chapter:"1200", topic:"Pre-Appeal", q:"A pre-appeal brief request for review must be filed:",
    choices:["With the appeal brief","With the notice of appeal","After the examiner's answer","After the PTAB decision"], answer:1,
    explain:"A pre-appeal brief request for review is filed concurrently with the notice of appeal and may resolve clear errors before the full briefing.",
    cite:"MPEP §1204.02"},

  // ─────────────────────── Chapter 1500 — Designs ───────────────────────
  {chapter:"1500", topic:"Design Term", q:"The term of a design patent issued from an application filed on or after May 13, 2015 is:",
    choices:["14 years from issue","15 years from issue","20 years from filing","17 years from issue"], answer:1,
    explain:"Design patents filed on or after May 13, 2015 have a term of 15 years from issuance (Hague Agreement implementation). Earlier-filed designs were 14 years.",
    cite:"MPEP §1505"},
  {chapter:"1500", topic:"Design Priority", q:"The foreign priority period for a design application is:",
    choices:["3 months","6 months","12 months","18 months"], answer:1,
    explain:"Design applications have a 6-month Paris Convention priority window (versus 12 months for utility).",
    cite:"MPEP §1504.10"},

  // ─────────────────────── Chapter 1800 — PCT ───────────────────────
  {chapter:"1800", topic:"PCT National Phase", q:"The deadline for entering the U.S. national phase from a PCT application is:",
    choices:["12 months from PCT filing","20 months from priority","30 months from priority","31 months from priority"], answer:2,
    explain:"The U.S. requires national-phase entry by 30 months from the earliest priority date under 35 U.S.C. 371. (Some other PCT offices use 31 months.)",
    cite:"MPEP §1893"},
  {chapter:"1800", topic:"PCT Filing", q:"Which is NOT a requirement for an international filing date in a PCT application?",
    choices:["At least one applicant who is a national or resident of a PCT contracting state","A description","At least one claim","Payment of the search fee"], answer:3,
    explain:"For an international filing date, you need an applicant entitled to file, indication it is an international application, description, claim(s), and a designation. Fees may be paid later.",
    cite:"MPEP §1810"},
  {chapter:"1800", topic:"PCT Demand", q:"To obtain an International Preliminary Examination Report (IPRP Chapter II), the applicant must file a Demand within:",
    choices:["3 months from the ISR or 22 months from priority, whichever is later","12 months from filing","30 months from priority","6 months from filing"], answer:0,
    explain:"A Demand for Chapter II preliminary examination must be filed within 3 months from transmittal of the ISR/written opinion or 22 months from priority, whichever is later.",
    cite:"MPEP §1864"},

  // ─────────────────────── Chapter 2000 — Duty of Disclosure ───────────────────────
  {chapter:"2000", topic:"Duty of Candor", q:"The duty of disclosure under 37 CFR 1.56 applies to:",
    choices:["Only the named inventors","Only the attorney of record","Each individual associated with the filing and prosecution","Only the assignee"], answer:2,
    explain:"The duty extends to each inventor, each attorney or agent involved, and every other person substantively involved in preparation or prosecution.",
    cite:"MPEP §2001.01"},
  {chapter:"2000", topic:"IDS", q:"To have an IDS considered without a fee or statement, it generally must be filed:",
    choices:["Within 3 months of filing or before first office action on the merits, whichever is later","Anytime before allowance","Within 1 month of filing","Within 6 months of any office action"], answer:0,
    explain:"Under 37 CFR 1.97(b), an IDS is considered without fee or statement if filed within 3 months of filing or national-stage entry, or before a first office action on the merits — whichever is later.",
    cite:"MPEP §609.04(b)"},

  // ─────────────────────── Chapter 2100 — Patentability ───────────────────────
  {chapter:"2100", topic:"§101", q:"Which is NOT a statutory category of invention under 35 U.S.C. 101?",
    choices:["Process","Machine","Manufacture","Idea"], answer:3,
    explain:"The four statutory categories are process, machine, manufacture, and composition of matter. Abstract ideas, laws of nature, and natural phenomena are judicial exceptions.",
    cite:"MPEP §2106"},
  {chapter:"2100", topic:"Alice/Mayo", q:"Under the Alice/Mayo two-step framework, step one asks:",
    choices:["Whether the claim is novel","Whether the claim is directed to a judicial exception","Whether the claim is enabled","Whether the claim is definite"], answer:1,
    explain:"Step 2A asks whether the claim is directed to an abstract idea, natural phenomenon, or law of nature. Step 2B asks whether additional elements amount to significantly more.",
    cite:"MPEP §2106.04"},
  {chapter:"2100", topic:"§102 AIA", q:"Under AIA 35 U.S.C. 102(b)(1)(A), the one-year grace period applies to disclosures:",
    choices:["By anyone, anytime","By the inventor or one who obtained the subject matter from the inventor","Only after issuance","Only foreign filings"], answer:1,
    explain:"The AIA grace period excludes from prior art disclosures made 1 year or less before filing by the inventor, joint inventor, or one who obtained the subject matter from them.",
    cite:"MPEP §2153"},
  {chapter:"2100", topic:"§103 Obviousness", q:"Under Graham v. John Deere, the obviousness analysis considers all EXCEPT:",
    choices:["Scope and content of the prior art","Differences between prior art and claims","Level of ordinary skill","Commercial intent of the applicant"], answer:3,
    explain:"Graham factors: (1) scope/content of prior art, (2) differences, (3) level of ordinary skill, and (4) secondary considerations like commercial success, long-felt need, failure of others.",
    cite:"MPEP §2141"},
  {chapter:"2100", topic:"§112(a) Enablement", q:"The enablement requirement is judged from the perspective of:",
    choices:["A layperson","A person of ordinary skill in the art at the time of filing","The inventor","The examiner"], answer:1,
    explain:"Enablement is judged by whether a person of ordinary skill in the art at the time of filing could make and use the invention without undue experimentation (Wands factors).",
    cite:"MPEP §2164"},
  {chapter:"2100", topic:"§112(b) Definiteness", q:"Under Nautilus, a claim is indefinite if:",
    choices:["It uses any functional language","It fails to inform those skilled in the art with reasonable certainty of the scope","It is broader than the preferred embodiment","It uses means-plus-function language"], answer:1,
    explain:"Nautilus (2014) replaced 'insolubly ambiguous' with 'reasonable certainty.' Claims must inform skilled artisans with reasonable certainty about their scope.",
    cite:"MPEP §2173"},
  {chapter:"2100", topic:"§112(f) Means-Plus-Function", q:"35 U.S.C. 112(f) means-plus-function claims are construed to cover:",
    choices:["Any structure for performing the function","The corresponding structure in the spec and equivalents","The literal claim language only","Only the preferred embodiment"], answer:1,
    explain:"Under §112(f), means-plus-function claims cover the corresponding structure described in the specification and equivalents thereof.",
    cite:"MPEP §2181"},
  {chapter:"2100", topic:"§102(a)(1)", q:"Under AIA §102(a)(1), a claimed invention is not patentable if it was:",
    choices:["Patented, described in a printed publication, in public use, on sale, or otherwise available to the public before the effective filing date","Known only outside the U.S.","Disclosed by the inventor 2 years before filing","Disclosed only orally"], answer:0,
    explain:"AIA §102(a)(1) creates a global novelty bar covering patents, printed publications, public use, on-sale activity, and any other public availability — regardless of geography.",
    cite:"MPEP §2152"},
  {chapter:"2100", topic:"Anticipation", q:"For anticipation under §102, the prior art reference must:",
    choices:["Disclose each and every claim element, arranged as in the claim","Suggest the invention","Render the claim obvious","Be in the same field of endeavor"], answer:0,
    explain:"Anticipation requires that a single prior art reference disclose every element of the claim, arranged as in the claim — explicitly or inherently.",
    cite:"MPEP §2131"},
  {chapter:"2100", topic:"Double Patenting", q:"A nonstatutory (obviousness-type) double patenting rejection can typically be overcome by:",
    choices:["Filing a continuation","Filing a terminal disclaimer","Cancelling the claims","Filing an appeal"], answer:1,
    explain:"A terminal disclaimer disclaiming the term of the later patent extending beyond the earlier patent overcomes nonstatutory double patenting (and ties enforceability to common ownership).",
    cite:"MPEP §804.02"},

  // ─────────────────────── Chapter 2200 — Reexamination ───────────────────────
  {chapter:"2200", topic:"Ex Parte Reexam", q:"Ex parte reexamination may be requested:",
    choices:["By any person, anytime during enforceability","Only by the patent owner","Only within 9 months of issuance","Only after litigation"], answer:0,
    explain:"Anyone, including the patent owner or a third party (even anonymously), may request ex parte reexamination based on patents or printed publications anytime during enforceability.",
    cite:"MPEP §2209"},
  {chapter:"2200", topic:"SNQ", q:"A reexamination request must raise:",
    choices:["A substantial new question of patentability","Any defect in the patent","Issues under §101","Issues under §112"], answer:0,
    explain:"The request must raise a substantial new question of patentability (SNQ) based on patents or printed publications.",
    cite:"MPEP §2242"},

  // ─────────────────────── Chapter 2500 — Maintenance Fees ───────────────────────
  {chapter:"2500", topic:"Maintenance Fees", q:"U.S. utility patent maintenance fees are due at:",
    choices:["3, 7, and 11 years from issuance","3.5, 7.5, and 11.5 years from issuance","4, 8, and 12 years from issuance","Every year"], answer:1,
    explain:"Maintenance fees are due 3.5, 7.5, and 11.5 years from the date of issuance. A 6-month grace period (with surcharge) follows each due date.",
    cite:"MPEP §2506"},
  {chapter:"2500", topic:"Design Patents", q:"Design patents require maintenance fees:",
    choices:["Yes, the same as utility","Yes, but at different intervals","No","Only if licensed"], answer:2,
    explain:"Design and plant patents do not require maintenance fees — only utility patents.",
    cite:"MPEP §2506"},

  // ─────────────────────── Chapter 2700 — Patent Term ───────────────────────
  {chapter:"2700", topic:"Patent Term", q:"The term of a U.S. utility patent filed on or after June 8, 1995 is:",
    choices:["17 years from issue","20 years from earliest U.S. nonprovisional filing date","20 years from issue","17 years from filing"], answer:1,
    explain:"Utility patents from applications filed on or after June 8, 1995 have a 20-year term from the earliest non-provisional U.S. or PCT filing date (provisionals don't count).",
    cite:"MPEP §2701"},
  {chapter:"2700", topic:"PTA", q:"Patent Term Adjustment (PTA) compensates for:",
    choices:["Inventor delay","USPTO delay during prosecution","Maintenance fee delays","Foreign filing delays"], answer:1,
    explain:"PTA compensates for certain USPTO delays (A, B, and C delays) during prosecution, reduced by applicant-caused delays.",
    cite:"MPEP §2731"},

  // ─────────────────────── Chapter 1400 — Reissue & Correction ───────────────────────
  {chapter:"1400", topic:"Reissue", q:"A broadening reissue must be filed within:",
    choices:["1 year of issuance","2 years of issuance","6 months of issuance","Anytime during the patent term"], answer:1,
    explain:"A reissue that enlarges the scope of the claims (broadening reissue) must be applied for within 2 years from the grant of the original patent.",
    cite:"MPEP §1412.03"},
  {chapter:"1400", topic:"Certificate of Correction", q:"A Certificate of Correction is appropriate for:",
    choices:["Adding new matter","Correcting USPTO mistakes or minor applicant mistakes of a clerical nature","Broadening claims","Changing inventorship after litigation"], answer:1,
    explain:"Certificates of Correction (37 CFR 1.322, 1.323) fix clerical/typographical errors — by the Office or by the applicant if of minor character and in good faith.",
    cite:"MPEP §1481"},

  // ─────────────────────── Chapter 300 — Ownership/Assignment ───────────────────────
  {chapter:"300", topic:"Recording", q:"An assignment is void against a subsequent purchaser without notice unless recorded within:",
    choices:["1 month of execution","3 months of execution, or before the subsequent purchase","6 months of execution","1 year of execution"], answer:1,
    explain:"Per 35 U.S.C. 261, an unrecorded assignment is void against a subsequent purchaser for valuable consideration without notice unless recorded within 3 months of execution or prior to the subsequent purchase.",
    cite:"MPEP §317"},

  // ─────────────────────── Chapter 400 — Representative ───────────────────────
  {chapter:"400", topic:"POA", q:"A power of attorney in an application filed on or after September 16, 2012 must generally be signed by:",
    choices:["The inventor only","The applicant (which may be the assignee)","The USPTO Director","Any registered attorney"], answer:1,
    explain:"Post-AIA, the applicant (which may be the assignee or obligated assignee) signs the POA. The applicant is the entity prosecuting the application.",
    cite:"MPEP §402.02(a)"},

  // ─────────────────────── Chapter 500 — Receipt/Filing ───────────────────────
  {chapter:"500", topic:"Filing Date", q:"For a nonprovisional utility application filed on or after Dec 18, 2013, a filing date requires:",
    choices:["A specification, claim, drawing, and fees","A specification (which may be by reference to a previously filed application); claims and drawings can be filed later in some cases","An oath","A complete IDS"], answer:1,
    explain:"After Dec 18, 2013 (PLTIA), a filing date requires only a specification (claim no longer required on filing for nonprovisionals — though missing claims will be required by notice). Pre-PLTIA rules required at least one claim.",
    cite:"MPEP §506"},

  // ─────────────────────── Chapter 1300 — Allowance ───────────────────────
  {chapter:"1300", topic:"Issue Fee", q:"After a Notice of Allowance, the issue fee must be paid within:",
    choices:["1 month, non-extendable","3 months, non-extendable","3 months, extendable","6 months, extendable"], answer:1,
    explain:"The issue fee must be paid within 3 months of the Notice of Allowance. This period is statutory and NOT extendable.",
    cite:"MPEP §1306"},
  {chapter:"1300", topic:"After Allowance", q:"An amendment after allowance under 37 CFR 1.312 is:",
    choices:["A matter of right","Subject to examiner approval","Not permitted","Always entered with a fee"], answer:1,
    explain:"Amendments after allowance under 1.312 are not a matter of right — entry requires good and sufficient reasons and examiner/supervisor approval.",
    cite:"MPEP §1302.04"},

  // ─────────────────────── Chapter 1100 — Pre-Grant Publication ───────────────────────
  {chapter:"1100", topic:"Publication", q:"A U.S. nonprovisional utility application is published:",
    choices:["Immediately upon filing","18 months from the earliest filing date for which a benefit is sought","Only upon allowance","Never"], answer:1,
    explain:"Under 35 U.S.C. 122(b), applications are published 18 months from the earliest claimed priority date, unless a non-publication request is filed and the applicant certifies no foreign filing.",
    cite:"MPEP §1120"},
  {chapter:"1100", topic:"Non-Publication Request", q:"A non-publication request must be filed:",
    choices:["With the application","Within 18 months","Anytime before publication","After allowance"], answer:0,
    explain:"A non-publication request must be filed at the time of filing the application and requires certification that the invention has not been and will not be filed abroad.",
    cite:"MPEP §1122"},

  // ─────────────────────── Chapter 100 — Secrecy/Access ───────────────────────
  {chapter:"100", topic:"Secrecy Orders", q:"A secrecy order issued under 35 U.S.C. 181:",
    choices:["Prevents publication and grant while in effect","Is permanent","Voids the application","Allows foreign filing"], answer:0,
    explain:"A secrecy order keeps the application secret, prevents publication or grant, and prohibits unauthorized export of the subject matter while in effect.",
    cite:"MPEP §120"},
  {chapter:"100", topic:"Foreign Filing License", q:"A foreign filing license is required when:",
    choices:["Filing any U.S. application","Filing abroad before a U.S. application or within 6 months of U.S. filing","Filing a PCT only","Never"], answer:1,
    explain:"Under 35 U.S.C. 184, an inventor must obtain a foreign filing license before filing abroad if no U.S. filing has been made, or within 6 months of a U.S. filing (the license is often granted on the filing receipt).",
    cite:"MPEP §140"},

  // ─────────────────────── Chapter 900 — Prior Art Search ───────────────────────
  {chapter:"900", topic:"Classification", q:"The USPTO primary classification system used today is:",
    choices:["USPC","CPC","IPC","Locarno"], answer:1,
    explain:"The Cooperative Patent Classification (CPC), jointly developed with the EPO, replaced the U.S. Patent Classification (USPC) for utility applications in 2015.",
    cite:"MPEP §905"},

  // ─────────────────────── Chapter 1600 — Plants ───────────────────────
  {chapter:"1600", topic:"Plant Patent", q:"A plant patent under 35 U.S.C. 161 covers:",
    choices:["Any new plant","Asexually reproduced, distinct and new variety of plant (other than tuber-propagated or uncultivated)","Sexually reproduced plants","Genetically modified plants only"], answer:1,
    explain:"Plant patents cover distinct and new varieties of plants asexually reproduced (e.g., by cuttings), excluding tuber-propagated and uncultivated plants found in nature.",
    cite:"MPEP §1601"},

  // ─────────────────────── Chapter 2800 — Supplemental Examination ───────────────────────
  {chapter:"2800", topic:"Supplemental Exam", q:"Supplemental examination under 35 U.S.C. 257 may be requested by:",
    choices:["Anyone","Only the patent owner","Only the inventor","Only the examiner"], answer:1,
    explain:"Only the patent owner may request supplemental examination, which can immunize the patent against certain inequitable conduct defenses if the SNQ is resolved.",
    cite:"MPEP §2801"},

  // ─────────────────────── Misc/Advanced ───────────────────────
  {chapter:"700", topic:"Restriction Practice", q:"Election by original presentation occurs when:",
    choices:["A new claim presented after action is to a non-elected invention","An applicant amends to add prior art","An RCE is filed","A restriction is traversed"], answer:0,
    explain:"If applicant presents new claims after a restriction that are directed to a non-elected invention or one not originally claimed, those claims are subject to election by original presentation and may be withdrawn.",
    cite:"MPEP §821.03"},
  {chapter:"2100", topic:"Inherency", q:"For a prior art reference to inherently anticipate, the missing element must be:",
    choices:["Probable","Possible","Necessarily present in the reference","Suggested by the reference"], answer:2,
    explain:"Inherency requires that the missing characteristic is necessarily present in the reference — not merely probable or possible. Recognition by skilled artisans is not required.",
    cite:"MPEP §2112"},
  {chapter:"2100", topic:"Printed Publication", q:"For a document to be a 'printed publication' under §102, it must be:",
    choices:["Mass-produced","Sufficiently accessible to the interested public","Indexed in a library","In English"], answer:1,
    explain:"A printed publication is one that has been made sufficiently accessible to the interested public exercising reasonable diligence. Even a single thesis cataloged in a library can qualify.",
    cite:"MPEP §2128"},
  {chapter:"2100", topic:"On-Sale Bar", q:"Under AIA §102(a)(1), the on-sale bar requires:",
    choices:["A completed sale in the U.S. only","A commercial offer for sale of a ready-for-patenting invention","Any internal company use","Public knowledge of price"], answer:1,
    explain:"Pfaff/Helsinn: the on-sale bar requires (1) a commercial offer for sale and (2) the invention being ready for patenting. AIA extends this to global sales and includes secret sales (Helsinn).",
    cite:"MPEP §2152.02(d)"},
  {chapter:"2100", topic:"Written Description", q:"The written description requirement is satisfied if the disclosure shows the inventor:",
    choices:["Built the invention","Had possession of the claimed invention as of the filing date","Reduced the invention to practice","Disclosed the best mode"], answer:1,
    explain:"Written description requires the spec to demonstrate that the inventor had possession of the claimed subject matter as of the filing date — separate from enablement.",
    cite:"MPEP §2163"},
  {chapter:"1200", topic:"Examiner's Answer", q:"After the examiner's answer, the applicant may file a reply brief within:",
    choices:["1 month","2 months, non-extendable under 1.136(a)","3 months","6 months"], answer:1,
    explain:"A reply brief may be filed within 2 months of the examiner's answer. This period is NOT extendable under 1.136(a).",
    cite:"MPEP §1208"},
  {chapter:"600", topic:"New Matter", q:"New matter introduced into the specification after filing is:",
    choices:["Permissible with a fee","Prohibited under 35 U.S.C. 132","Allowed only in a CIP","Allowed in a divisional"], answer:1,
    explain:"35 U.S.C. 132 prohibits introducing new matter into the disclosure of an application. New matter can only be added by filing a CIP (where it gets the CIP's filing date).",
    cite:"MPEP §608.04"},
  {chapter:"200", topic:"Provisional Benefit", q:"To claim benefit of a provisional, the later application must be filed within:",
    choices:["6 months of the provisional","12 months of the provisional (extendable by 2 months in some cases)","18 months","24 months"], answer:1,
    explain:"35 U.S.C. 119(e) requires the nonprovisional to be filed within 12 months of the provisional. The PLTIA permits a 2-month restoration in limited unintentional-delay cases.",
    cite:"MPEP §211.01(a)"},
  {chapter:"700", topic:"Abandonment", q:"An application becomes abandoned when:",
    choices:["The applicant misses any due date","No reply is filed within the statutory period for reply","The examiner refuses an interview","An IDS is rejected"], answer:1,
    explain:"Failure to reply to an office action within the statutory period for reply (max 6 months) results in abandonment, absent revival.",
    cite:"MPEP §711"},
  {chapter:"700", topic:"Revival", q:"To revive an abandoned application under 1.137, the applicant must show the delay was:",
    choices:["Excusable","Reasonable","Unintentional","Inadvertent and excusable"], answer:2,
    explain:"Under 37 CFR 1.137, revival requires a petition, the prescribed fee, the required reply, and a statement that the entire delay was unintentional.",
    cite:"MPEP §711.03(c)"},

  // ─────────────────────── More Ch 2100 (heavily tested) ───────────────────────
  {chapter:"2100", topic:"Teaching Away", q:"A prior art reference 'teaches away' when:",
    choices:["It is in a different field","It would lead a skilled person in a direction divergent from the claimed invention","It is silent on the issue","It pre-dates the claimed invention"], answer:1,
    explain:"A reference teaches away when it criticizes, discredits, or otherwise discourages following the claimed path. Mere silence is not teaching away.",
    cite:"MPEP §2145"},
  {chapter:"2100", topic:"Secondary Considerations", q:"Which is NOT a recognized secondary consideration of nonobviousness?",
    choices:["Commercial success","Long-felt but unsolved need","Failure of others","Inventor's effort"], answer:3,
    explain:"Recognized secondary considerations include commercial success, long-felt need, failure of others, copying, unexpected results, skepticism, and praise. The inventor's personal effort is not one.",
    cite:"MPEP §2145"},
  {chapter:"2100", topic:"Analogous Art", q:"Prior art is analogous to the claimed invention if it is:",
    choices:["From the same field of endeavor, OR reasonably pertinent to the problem","From the same company","Cited in the IDS","Less than 10 years old"], answer:0,
    explain:"Two-prong test: same field of endeavor regardless of problem, OR reasonably pertinent to the particular problem the inventor was trying to solve.",
    cite:"MPEP §2141.01(a)"},
];

window.MPEP_CHAPTERS = {
  "100":"Secrecy, Access, National Security & Foreign Filing",
  "200":"Types, Cross-Noting & Status of Application",
  "300":"Ownership and Assignment",
  "400":"Representative of Applicant",
  "500":"Receipt and Handling of Mail and Papers",
  "600":"Parts, Form, and Content of Application",
  "700":"Examination of Applications",
  "800":"Restriction in Applications",
  "900":"Prior Art, Classification and Search",
  "1000":"Matters Decided by Various U.S. Patent and Trademark Office Officials",
  "1100":"Statutory Invention Registration & Pre-Grant Publication",
  "1200":"Appeal",
  "1300":"Allowance and Issue",
  "1400":"Correction of Patents",
  "1500":"Design Patents",
  "1600":"Plant Patents",
  "1700":"Miscellaneous",
  "1800":"Patent Cooperation Treaty (PCT)",
  "1900":"Protest",
  "2000":"Duty of Disclosure",
  "2100":"Patentability",
  "2200":"Citation of Prior Art and Ex Parte Reexamination",
  "2300":"Interference Proceedings",
  "2400":"Biotechnology",
  "2500":"Maintenance Fees",
  "2600":"Optional Inter Partes Reexamination",
  "2700":"Patent Terms and Extensions",
  "2800":"Supplemental Examination",
  "2900":"International Design Applications",
};
